---
title: "tab8_pjTime"
output: html_document
---

### **モジュール:** ***新規時点への投影***

**背景**  

簡単に言えば、ニッチ／分布モデルをモデル構築に使用したものとは異なる地域または時点に適用または「投影」するには、元の地域および時点で利用可能である場合に限って、モデルと説明変数の新しい値に基づく予測を行うことになります。しかし現実には、研究者は、非類似条件(例えば環境空間に外挿を必要とする。手順6: **モデル化**参照)および生物種の相互の影響の効果における不均質性を含めて、多くの落とし穴があり得ることを認識していなければなりません(Fitzpatrick and Hargrove 2009、Anderson 2013)。

異なる時点について予測するには、これら時点元での説明変数を記述するデータセットが必要です。<a href="http://www.ipcc-data.org/guidelines/pages/gcm_guide.html" target="_blank">大気大循環モデル</a>(GCM)からは過去と未来の両方について気候の推定値を得ることができます。様々なGCMによってまったく共通点のない推定値が出される場合がありますが、これはベースとなる仮定が異なるためです。現行のWallaceは、WorldClimのデータベースに基づく<a href="http://cmip-pcmdi.llnl.gov/cmip5/" target="_blank">IPPC5</a>の気候予測をベースとして2050年と2070年の将来の気候データを使用しています。将来のバージョンでは過去の時点(例えば、最終氷河期、完新世中期など)に投影できる機能性も備わるでしょう。

**実装** 

このモジュールでは、モデル予測グリッドの機能にRパッケージの`dismo`を使用します。

ユーザーはまずモデルを選択します。手順6: **モデル化**で選択した`ENMeval`の設定によっては、Maxentの選択肢が複数になる場合があります。次に、地図上に多角形を描いて新たに予測を実施する区域の輪郭を決めます。多角形を描いたら、この範囲をSelectですべての投影操作に選択します。次にユーザーは投影する時点(2050年または2070年)、さらに未来の気候を推定するGCMを選択しなければなりません。Projectは選択した範囲の各セルの説明変数値に対するモデル化した応答を計算し、予測を地図上にプロットします。予測値は分析に使用するラスタグリッドタイプ(.grdおよび.asc)か画像ファイル(.png)のどちらかの形式でダウンロードできます。

次に、ユーザーは連続予測をバイナリ予測(0と1)に変換するための閾値設定ルールを選択することができますが、これは存在／不在または好適度／不好適度を示すと解釈できます。閾値設定ルールについて詳しくは、**手順6: モデル化**の手引書を参照してください。モデルと閾値を選択した後は、地図上に予測をプロットすることができ、予測値は分析に使用するラスタグリッドタイプ(.grdおよび.asc)か画像ファイル(.png)のどちらかの形式でダウンロードできます。

*注意* ：しかしながら、maxent.jarオプションでは、モデル予測は現在、トレーニングデータセットより極端な環境値のあるグリッドセル(背景サンプル＋在データレコード)について、常に「クランプ」されるようになっています。これは、dismoにおける`predict()`関数のバグによるもので、モデル予測では「クランプする」オプションが常にオンになっています(すなわち、`dismo`を使ってクランプをオフにしてトレーニングデータセットの環境条件を超える無制約の外挿をすることはできません)。

**引用文献**

Anderson R.P. (2013). A framework for using niche models to estimate impacts of climate change on species distributions. *Annals of the New York Academy of Sciences*. 1297: 8-28.

Fitzpatrick, M. C., & Hargrove, W. W. (2009). The projection of species distribution models and the problem of non-analog climate. *Biodiversity and Conservation*. 18: 2255-2261.
