---
title: "comp3"
output: html_document
---

### **手順3: 環境データ取得**

**はじめに**

ニッチ／分布モデリングのアルゴリズムには在データの他に環境説明変数を必要とします(Franklin 2010 chap. 5、Peterson et al. 2011 chap. 6)。手順3: **環境データ取得**は、これらの変数をオンラインソースからラスタグリッドの形式で入手できるようにするものです。近年、気候データのグローバルなデータベースがいくつか登場しています(Hijmans et al. 2005、Kriticos et al. 2012、Sbrocco and Barber 2013、Karger et al. 2016)。現行の*Wallace* には環境データについて2つのオプションがあります。まず、WorldClimデータセットの現在の平均気候データにアクセスできます。これは陸上地域をほぼ世界的にカバーしています(モジュール ***WorldClim***)。これに代わって、もうひとつのオプションではユーザーが環境ラスタグリッドをアップロードすることができます (モジュール ***ユーザー指定の環境データ)***。

将来のリリース版では、他の陸上気候データセット(異なる補間方法を用いるCHELSA、または異なる変数を用いるCliMondなど)、海洋気候データセット(例：MARSPECなど)、植生、土地被覆、および土地利用データを実装する予定です。

**引用文献**

Franklin J. (2010). Mapping Species Distributions: Spatial Inference and Prediction. Data for species distribution models: the environmental data. In: Mapping species distributions: spatial inference and prediction. Cambridge: Cambridge University Press.

Hijmans, R. J., Cameron, S. E., Parra, J. L., Jones, P. G., & Jarvis, A. (2005). Very high resolution interpolated climate surfaces for global land areas. *International Journal of Climatology*.  25: 1965-1978.

Karger, D.N., Conrad, O., Böhner, J., Kawohl, T., Kreft, H., Soria-Auza, R.W., Zimmermann, N.E, Linder, H.P. & Kessler, M. (2016). CHELSA climatologies at high resolution for the earth's land surface areas (Version 1.1). World Data Center for Climate. doi:10.1594/WDCC/CHELSA_v1_1. http://dx.doi.org/doi:10.1594/WDCC/CHELSA_v1_1

Kriticos, D. J., Webber, B. L., Leriche, A., Ota, N., Macadam, I., Bathols, J., & Scott, J. K. (2012). CliMond: global high-resolution historical and future scenario climate surfaces for bioclimatic modelling. *Methods in Ecology and Evolution*. 3: 53-64.

Peterson A. T., Soberón J., Pearson R. G., Anderson R. P., Martinez-Meyer E., Nakamura M., Araújo M. B. (2011). Environmental Data. In: *Ecological Niches and Geographic Distributions*. Princeton, New Jersey: Monographs in Population Biology, 49. Princeton University Press.

Sbrocco, E. J., & Barber, P. H. (2013). MARSPEC: ocean climate layers for marine spatial ecology. *Ecology*. 94: 979-979.
