---
title: "tab5_spatial"
output: html_document
---

### **モジュール:** ***空間的分割***

**背景**

サンプリングバイアスが知られているか、または疑われる場合、およびモデルの応用対象が時空間的にモデル構築範囲と異なる場合、空間的分割には非空間的分割よりもはるかに優れた利点があります。このような応用を想定している場合、モデルの最終的な用途に必要と考えられる環境的外挿の程度に似た空間分割のスキーム(侵略的生物種についての別地域での予測、または気候変動研究においての将来予測など) を用いるのが望ましいでしょう。

**実装**

このモジュールは、Rパッケージの`ENMeval`の機能を実施して在データの位置をトレーニングおよびテスト用データセットに分割します。

空間分割には、1) 「ブロック」、2)「碁盤格子1」、または3)「碁盤格子2」の3つの方法のうち、どれか1つを選びます。2)と3)を選択した集合因数の強度によっては、これら3つの分割方法は、分割領域の間での地点の空間的独立性が(および保留した地点に対応した予測をするための環境的外挿の必要性も)異なります。「ブロック｣の方法では、まず緯度、次に経度のラインを引いて、空間を表す長方形に対応する位置のグループを4つ作成します(k=4)。これらの長方形には類似した数の位置が入っていますが、区域が異なるのが普通です。「碁盤格子1」の方法では、範囲を格子状に分け、どの正方形にあるかに基づいて位置を2つのグループのいずれかに帰属させます(k=2)。「碁盤格子2」の方法も類似していますが、空間のグループ分けに階層をもう一段追加することで、k=4グループを作成します。具体的には、ユーザー指定のきめの細かいグリッドの長さを掛けた「集合因数」に等しい、グリッドサイズの粗い碁盤格子を「碁盤格子１」の上に置きます。Wallaceの後続バージョンでは、分割法について、より洗練された近傍法などの他の変数が使用できると予想されます。これら分割方法について詳しくはMuscarella et al. (2014)を参照してください。ここまでの段階で保持したすべての位置に分割領域グループの列を加えたファイルは、手順4: **環境データの処理**でサンプルした背景地点すべてと共に.csv形式でダウンロードできます。

**引用文献**

Muscarella R., Galante P.J., Soley-Guardia M., Boria R.A., Kass J.M., Uriarte M., Anderson R.P. (2014). ENMeval: An R package for conducting spatially independent evaluations and estimating optimal model complexity for Maxent ecological niche models. *Methods in Ecology and Evolution*. 5: 1198-1205.
