source("funcs/functions.R", local = TRUE)

# load modules
for (f in list.files('./modules')) {
  source(file.path('modules', f), local=TRUE)
}

# Define UI for application
shinyUI(tagList(
  shinyjs::useShinyjs(),
  navbarPage(theme=bslib::bs_theme(version = 3, 
                                   bootswatch = "united"), 
             id='tabs', collapsible=TRUE,
             title='Wallace',
             tabPanel(i18n$t("Intro"), value=0),
             tabPanel(i18n$t("1 Occ Data"), value=1),
             tabPanel(i18n$t("2 Process Occs"), value=2),
             tabPanel(i18n$t("3 Env Data"), value=3),
             tabPanel(i18n$t("4 Process Envs"), value=4),
             tabPanel(i18n$t("5 Partition Occs"), value=5),
             tabPanel(i18n$t("6 Model"), value=6),
             tabPanel(i18n$t("7 Visualize"), value=7),
             tabPanel(i18n$t("8 Project"), value=8),
             tabPanel(i18n$t("Session Code"), value='rmd'),
             fluidRow(column(4,
                             wellPanel(
                               includeCSS("css/styles.css"),
                               includeScript("js/scroll.js"),
                               conditionalPanel("input.tabs == 0",
                                                #actionButton('load', 'HACK'),
                                                includeMarkdown("Rmd/text_intro_tab.Rmd")
                               ),
                               # COMPONENT 1 ####
                               conditionalPanel("input.tabs == 1",
                                                h4(i18n$t("Obtain Occurrence Data")),
                                                radioButtons("occSel", i18n$t("Modules Available:"),
                                                             #choices = list("Query Database" = 'db', "User-specified" = 'user'),
                                                             choiceNames = list(i18n$t("Query Database"), i18n$t("User-specified")),
                                                             choiceValues = list('db', 'user'),
                                                             selected = 'db'),
                                                HTML('<hr>'),
                                                conditionalPanel("input.occSel == 'db'",
                                                                 div(i18n$t("Module: Query Database"), id="mod"),
                                                                 uiTop('spocc', i18n$t("Interface to Species Occurrence Data Sources")),
                                                                 HTML('<hr>'),
                                                                 queryDb_UI('c1_queryDb'),
                                                                 actionButton("goDbOccs", i18n$t("Query Database")), br(), br(),
                                                                 HTML('<hr>'),
                                                                 strong(i18n$t("Download database occurrence localities (.csv)")), br(), br(),
                                                                 downloadButton('dlDbOccs', i18n$t("Download")),
                                                                 HTML('<hr>'),
                                                                 uiBottom("Jamie M. Kass, Bruno Vilela, Robert P. Anderson", 'spocc', "Scott Chamberlain, Karthik Ram, Ted Hart")
                                                ),
                                                conditionalPanel("input.occSel == 'user'",
                                                                 div(i18n$t("Module: User-specified Occurrences"), id="mod"),
                                                                 HTML('<hr>'),
                                                                 userOccs_UI('c1_userOccs'),
                                                                 actionButton("goUserOccs", i18n$t("Load Occurrences")),
                                                                 HTML('<hr>'),
                                                                 div('Module Developers: Jamie M. Kass, Bruno Vilela, Robert P. Anderson', id="pkgDes")
                                                )
                               ),
                               # COMPONENT 2 ####
                               conditionalPanel("input.tabs == 2",
                                                h4(i18n$t("Process Occurrence Data")),
                                                radioButtons("procOccSel", i18n$t("Modules Available:"),
                                                             #choices = list("Select Occurrences On Map" = 'selOccs',
                                                             #               "Remove Occurrences By ID" = 'remID',
                                                             #               "Spatial Thin" = 'spthin')),
                                                             choiceNames = list(i18n$t("Select Occurrences On Map"), i18n$t("Remove Occurrences By ID"), i18n$t("Spatial Thin")),
                                                             choiceValues = list('selOccs', 'remID', 'spthin')),               
                                                HTML('<hr>'),
                                                conditionalPanel("input.procOccSel == 'selOccs'",
                                                                 div(i18n$t("Module: Select Occurrences On Map"), id="mod"),
                                                                 uiTop('leaflet.extras', i18n$t("Extra functionality for 'leaflet' Package")),
                                                                 HTML('<hr>'),
                                                                 selectOccs_UI('c2_selectOccs'),
                                                                 strong(i18n$t("Select occurrences intersecting drawn polygon")), br(),
                                                                 "(", HTML("<font color='blue'><b>NOTE</b></font>"), 
                                                                 i18n$t(": to begin drawing click hexagon icon on map toolbar and when complete. press 'Finish' and then the 'Select Occurrences' button)"), br(), br(),
                                                                 actionButton("goSelectOccs", i18n$t("Select Occurrences"))
                                                ),
                                                conditionalPanel("input.procOccSel == 'remID'",
                                                                 div(i18n$t("Module: Remove Occurrences By ID"), id="mod"),
                                                                 HTML('<hr>'),
                                                                 removeByID_UI('c2_removeByID'),
                                                                 actionButton("goRemoveByID", i18n$t("Remove Occurrence"))
                                                ),
                                                # placeholder for select on map
                                                
                                                conditionalPanel("input.procOccSel == 'spthin'",
                                                                 div(i18n$t("Module: Spatial Thin"), id="mod"),
                                                                 uiTop('spThin', i18n$t("Spatial Thinning of Species Occurrence Records")),
                                                                 HTML('<hr>'),
                                                                 thinOccs_UI('c2_thinOccs'),
                                                                 actionButton("goThinOccs", i18n$t("Thin Occurrences"))
                                                ), br(),
                                                strong(i18n$t("Reset to original occurrences")), br(), br(),
                                                actionButton("goResetOccs", i18n$t("Reset")),
                                                HTML('<hr>'),
                                                strong(i18n$t("Download processed occurrence localities (.csv)")), br(), br(),
                                                downloadButton('dlProcOccs', i18n$t("Download")),
                                                HTML('<hr>'),
                                                conditionalPanel("input.procOccSel == 'selOccs'",
                                                                 uiBottom("Jamie M. Kass, Robert P. Anderson", 'leaflet.extras', 'Bhaskar Karambelkar, Bangyou Zheng')),
                                                conditionalPanel("input.procOccSel == 'remID'",
                                                                 uiBottom("Jamie M. Kass, Robert P. Anderson")),
                                                conditionalPanel("input.procOccSel == 'spthin'",
                                                                 uiBottom("Jamie M. Kass, Matthew E. Aiello-Lammens, Robert P. Anderson", 'spThin', "Matthew E. Aiello-Lammens, Rob A. Boria, 
                                                                                          Alex Radosavljevic, Bruno Vilela, Robert P. Anderson"),
                                                                 " | ", a("software note", href="http://onlinelibrary.wiley.com/doi/10.1111/ecog.01132/abstract", target = "_blank"))
                               ),
                               # COMPONENT 3 ####
                               conditionalPanel("input.tabs == 3",
                                                h4(i18n$t("Obtain Environmental Data")),
                                                radioButtons("envDataSel", i18n$t("Modules Available:"),
                                                             #choices = list("WorldClim Bioclims" = 'wcbc',
                                                             #               "User-specified" = 'user')),
                                                             choiceNames = list(i18n$t("WorldClim Bioclims"), i18n$t("User-specified")),
                                                             choiceValues = list('wcbc', 'user')),
                                                HTML('<hr>'),
                                                conditionalPanel("input.envDataSel == 'wcbc'",
                                                                 div(i18n$t("Module: WorldClim Bioclims"), id="mod"),
                                                                 uiTop('raster', i18n$t("Geographic Data Analysis and Modeling")),
                                                                 HTML('<hr>'),
                                                                 wcBioclims_UI("c3_wcBioclims"),
                                                                 strong(i18n$t("Using map center coordinates as reference for tile download.")),
                                                                 textOutput('ctrLatLon'), br(),
                                                                 actionButton("goEnvData", i18n$t("Load Env Data"))
                                                ),
                                                conditionalPanel("input.envDataSel == 'user'",
                                                                 div(i18n$t("Module: User-specified Environmental Data"), id="mod"),
                                                                 HTML('<hr>'),
                                                                 userEnvs_UI('c3_userEnvs'),
                                                                 actionButton('goUserEnvs', i18n$t("Load Env Data"))
                                                ),
                                                # br(), br(),
                                                # strong("Download environmental predictors"), br(), br(),
                                                # downloadButton('dlEnvs', "Download"),
                                                HTML('<hr>'),
                                                uiBottom("Jamie M. Kass, Gonzalo E. Pinilla-Buitrago, Robert P. Anderson", 'raster', "Robert J. Hijmans, Jacob van Etten, Joe Cheng, Matteo Mattiuzzu, 
                                                         Michael Sumner, Jonathan A. Greenberg, Oscar Perpinan Lamigueriro, Andrew Bevan, 
                                                         Etienne B. Racine, Ashton Shortridge"),
                                                " | ", a("WorldClim", href="http://worldclim.org", target="_blank")
                                                
                               ),
                               # COMPONENT 4 ####
                               conditionalPanel("input.tabs == 4",
                                                h4(i18n$t("Process Environmental Data")),
                                                radioButtons("envProcSel", i18n$t("Modules Available:"),
                                                             #choices = list("Select Study Region" = "bgSel",
                                                             #               "User-specified" = "bgUser")),
                                                             choiceNames = list(i18n$t("Select Study Region") , i18n$t("User-specified")),
                                                             choiceValues = list('bgSel', 'bgUser')),               
                                                
                                                HTML('<hr>'),
                                                conditionalPanel("input.envProcSel == 'bgSel'",
                                                                 div(i18n$t("Module: Select Study Region"), id="mod"),
                                                                 uiTop('sp', i18n$t("Title Classes and Methods for Spatial Data")),
                                                                 uiTop('rgeos', i18n$t("Interface to Geometry Engine - Open Source (GEOS)")),
                                                                 HTML('<hr>'),
                                                                 div(i18n$t("Step 1:"), id="step"), div(i18n$t("Choose Background Extent"), id="stepText"), br(), br(),
                                                                 bgExtent_UI('c4_bgExtent'),
                                                                 actionButton("goBgExt", i18n$t("Select"))),
                                                conditionalPanel("input.envProcSel == 'bgUser'",
                                                                 div(i18n$t("Module: User-specified Study Region"), id="mod"),
                                                                 div(i18n$t("Step 1:"), id="step"), div(i18n$t("Choose Background Extent"), id="stepText"), br(), br(),
                                                                 userBgExtent_UI('c4_userBgExtent'),
                                                                 actionButton("goUserBg", i18n$t("Load"))),
                                                conditionalPanel("input.envProcSel == 'bgSel' | input.envProcSel == 'bgUser'",
                                                                 HTML('<hr>'),
                                                                 div(i18n$t("Step 2:"), id="step"), div(i18n$t("Sample Background Points"), id="stepText"), br(), br(),
                                                                 strong(i18n$t("Mask predictor rasters by background extent and sample background points")), br(), br(),
                                                                 bgMskAndSamplePts_UI('c4_bgMskAndSamplePts'),
                                                                 actionButton("goBgMask", i18n$t("Sample")), br(), br(),
                                                                 HTML('<hr>'),
                                                                 selectInput('bgMskFileType', label = i18n$t("Select download file type"),
                                                                             choices = list("GRD" = 'raster', "ASCII" = 'ascii', "GeoTIFF" = 'GTiff')),
                                                                 strong(i18n$t("Download predictor rasters masked to background extent")), br(), br(),
                                                                 downloadButton('dlMskEnvs', i18n$t("Download")),
                                                                 HTML('<hr>'),
                                                                 uiBottom("Jamie M. Kass, Bruno Vilela, Robert P. Anderson", 'sp', "Edzer Pebesma, Roger Bivand, Barry Rowlingson, Virgilio Gomez-Rubio,
                                                                          Robert Hijmans, Michael Sumner, Don MacQueen, Jim Lemon, Josh O\'Brien"), br(),
                                                                 uiBottom(NULL, 'rgeos', "Roger Bivand, Colin Rundel, Edzer Pebesma, Karl Ove Hufthammer"))
                                                
                               ),
                               # COMPONENT 5 ####
                               conditionalPanel("input.tabs == 5",
                                                h4(i18n$t("Partition Occurrence Data")),
                                                radioButtons("partSel", i18n$t("Modules Available:"),
                                                             #choices = list("Non-spatial Partition" = 'nsp',
                                                             #               "Spatial Partition" = 'sp')),
                                                             choiceNames = list(i18n$t("Non-spatial Partition"), i18n$t("Spatial Partition")),
                                                             choiceValues = list('nsp', 'sp')),               
                                                HTML('<hr>'),
                                                conditionalPanel("input.partSel == 'sp'",
                                                                 div(i18n$t("Module: Spatial Partition"), id="mod"),
                                                                 uiTop('ENMeval', i18n$t("Automated Runs and Evaluations of Ecological Niche Models")),
                                                                 HTML('<hr>'),
                                                                 partSp_UI('c5_partSp'),
                                                                 actionButton("goPartSp", i18n$t("Partition"))),
                                                conditionalPanel("input.partSel == 'nsp'",
                                                                 div(i18n$t("Module: Non-spatial Partition"), id="mod"),
                                                                 uiTop('ENMeval', i18n$t("Automated Runs and Evaluations of Ecological Niche Models")),
                                                                 HTML('<hr>'),
                                                                 partNsp_UI('c5_partNsp'),
                                                                 actionButton("goPartNsp", i18n$t("Partition"))),
                                                HTML('<hr>'),
                                                strong(i18n$t("Download occurrence and background localities with partition values (.csv)")), br(), br(),
                                                downloadButton('dlPart', i18n$t("Download")),
                                                HTML('<hr>'),
                                                uiBottom("Jamie M. Kass, Bruno Vilela, Robert P. Anderson", 'ENMeval', 'Robert Muscarella, Peter J. Galante, Mariano Soley-Guardia, Robert A. Boria,
                                                                           Jamie M. Kass, Maria Uriarte, Robert P. Anderson'),
                                                " | ", a("software note", href="http://onlinelibrary.wiley.com/doi/10.1111/2041-210X.12261/abstract", target = "_blank")
                               ),
                               # COMPONENT 6 ####
                               conditionalPanel("input.tabs == 6",
                                                h4(i18n$t("Build and Evaluate Niche Model")),
                                                radioButtons("enmSel", i18n$t("Modules Available:"),
                                                             choices = list("BIOCLIM", "Maxent")),
                                                HTML('<hr>'),
                                                conditionalPanel("input.enmSel == 'Maxent'",
                                                                 div(i18n$t("Module: Maxent"), id="mod"),
                                                                 uiTop('ENMeval', i18n$t("Automated Runs and Evaluations of Ecological Niche Models using Maxent GUI (Java)")),
                                                                 uiTop('dismo', i18n$t("Species Distribution Modeling")),
                                                                 uiTop('maxnet', i18n$t("Fitting 'Maxent' Species Distribution Models with 'glmnet'")),
                                                                 HTML('<hr>'),
                                                                 htmlOutput('maxentJar'), br(),
                                                                 "(", HTML("<font color='blue'><b>NOTE</b></font>"), 
                                                                 i18n$t(": see module guidance for troubleshooting tips if you are experiencing problems.)"),
                                                                 HTML('<hr>'),
                                                                 maxent_UI('c6_maxent'),
                                                                 actionButton('goMaxent', i18n$t("Run"))),
                                                conditionalPanel("input.enmSel == 'BIOCLIM'",
                                                                 div(i18n$t("Module: BIOCLIM"), id="mod"),
                                                                 uiTop('ENMeval', i18n$t("Automated Runs and Evaluations of Ecological Niche Models")),
                                                                 uiTop('dismo', i18n$t("Species Distribution Modeling")),
                                                                 HTML('<hr>'),
                                                                 bioclim_UI('c6_bioclim'),
                                                                 actionButton('goBioclim', i18n$t("Run"))),
                                                HTML('<hr>'),
                                                downloadButton('dlEvalTbl', i18n$t("Download CSV")),
                                                HTML('<hr>'),
                                                uiBottom("Jamie M. Kass, Gonzalo E. Pinilla-Buitrago, Robert Muscarella, Bruno Vilela, Robert P. Anderson", 'ENMeval', 'Robert Muscarella, Peter J. Galante, Mariano Soley-Guardia, Robert A. Boria,
                                                         Jamie M. Kass, Maria Uriarte, Robert P. Anderson'),
                                                " | ", a("software note", href="http://onlinelibrary.wiley.com/doi/10.1111/2041-210X.12261/abstract", target = "_blank"), br(),
                                                uiBottom(NULL, 'dismo', 'Robert J. Hijmans, Steven Phillips, John Leathwick, Jane Elith'), br(),
                                                uiBottom(NULL, 'maxnet', 'Steven Phillips')
                               ),
                               # COMPONENT 7 ####
                               conditionalPanel("input.tabs == 7", 
                                                h4(i18n$t("Visualize Model Results")),
                                                radioButtons("visSel", i18n$t("Modules Available:"),
                                                             #choices = list("BIOCLIM Envelope Plots" = 'bcPlots',
                                                             #               "Maxent Evaluation Plots" = 'mxEval',
                                                             #               "Plot Response Curves" = 'response',
                                                             #               "Map Prediction" = 'map')),
                                                             choiceNames = list(i18n$t("BIOCLIM Envelope Plots"), i18n$t("Maxent Evaluation Plots"), i18n$t("Plot Response Curves"), i18n$t("Map Prediction")),
                                                             choiceValues = list('bcPlots', 'mxEval', 'response', 'map')),               
                                                HTML('<hr>'),
                                                conditionalPanel("input.visSel == 'bcPlots'",
                                                                 div(i18n$t("Module: BIOCLIM Envelope Plots"), id="mod"),
                                                                 uiTop('dismo', i18n$t("Species Distribution Modeling")),
                                                                 HTML('<hr>'),
                                                                 bcPlots_UI('c7_bcPlots')),
                                                conditionalPanel("input.visSel == 'mxEval'",
                                                                 div(i18n$t("Module: Maxent Evaluation Plots"), id="mod"),
                                                                 uiTop('ENMeval', i18n$t("Automated Runs and Evaluations of Ecological Niche Models")),
                                                                 uiTop('dismo', i18n$t("Species Distribution Modeling")),
                                                                 HTML('<hr>'),
                                                                 mxEvalPlots_UI('c7_mxEvalPlots')),
                                                conditionalPanel("input.visSel == 'response'",
                                                                 div(i18n$t("Module: Response Curves"), id="mod"),
                                                                 uiTop('dismo', i18n$t("Species Distribution Modeling")),
                                                                 HTML('<hr>'),
                                                                 respPlots_UI('c7_respPlots')),
                                                conditionalPanel("input.visSel == 'map'",
                                                                 div(i18n$t("Module: Map Prediction"), id="mod"),
                                                                 uiTop('dismo', i18n$t("Species Distribution Modeling")),
                                                                 HTML('<hr>'),
                                                                 conditionalPanel("input.enmSel == 'Maxent'", mapPredsMaxent_UI('c7_mapPredsMaxent')), 
                                                                 conditionalPanel("input.enmSel != 'Maxent'", mapPreds_UI('c7_mapPreds')),
                                                                 actionButton("goMapPreds", i18n$t("Plot")), br(), br(),
                                                                 HTML('<hr>'),
                                                                 selectInput('predFileType', label = i18n$t("Select download file type"),
                                                                             choices = list("GRD" = 'raster', "ASCII" = 'ascii', 
                                                                                            "GeoTIFF" = 'GTiff', "PNG" = "png")),
                                                                 strong(i18n$t("Download displayed raster")), br(), br(),
                                                                 downloadButton('dlPred', i18n$t("Download"))),
                                                HTML('<hr>'),
                                                conditionalPanel("input.visSel == 'mxEval'",
                                                                 uiBottom("Jamie M. Kass, Robert Muscarella, Bruno Vilela, Robert P. Anderson", 'ENMeval', 'Robert Muscarella, Peter J. Galante, Mariano Soley-Guardia, Robert A. Boria,
                                                         Jamie M. Kass, Maria Uriarte, Robert P. Anderson'),
                                                                 " | ", a("software note", href="http://onlinelibrary.wiley.com/doi/10.1111/2041-210X.12261/abstract", target = "_blank"), br()
                                                ),
                                                conditionalPanel("input.visSel != 'mxEval'",
                                                                 uiBottom("Jamie M. Kass, Gonzalo E. Pinilla-Buitrago, Bruno Vilela, Robert P. Anderson")
                                                ),
                                                uiBottom(NULL, 'dismo', 'Robert J. Hijmans, Steven Phillips, John Leathwick, Jane Elith')
                               ),
                               # COMPONENT 8 ####
                               conditionalPanel("input.tabs == 8",
                                                h4(i18n$t("Project Model")),
                                                radioButtons("projSel", i18n$t("Modules Available:"),
                                                             #choices = list("Project to New Extent" = 'projArea',
                                                             #               "Project to New Time" = 'projTime',
                                                             #               "Calculate Environmental Similarity" = 'mess'),
                                                             choiceNames = list(i18n$t("Project to New Extent"), i18n$t("Project to New Time"), i18n$t("Calculate Environmental Similarity")),
                                                             choiceValues = list('projArea', 'projTime', 'mess'),               
                                                             selected = 'projArea'),
                                                HTML('<hr>'),
                                                conditionalPanel("input.projSel == 'projArea'",
                                                                 div(i18n$t("Module: Project to New Extent"), id="mod"),
                                                                 uiTop('dismo', i18n$t("Species Distribution Modeling")),
                                                                 HTML('<hr>'),
                                                                 strong(i18n$t("Project model to new extent")), br(),
                                                                 em(i18n$t("Using the polygon drawing tool")), br(), br(),
                                                                 projectArea_UI('c8_projectArea'), 
                                                                 actionButton('goProjectArea', i18n$t("Project"))),
                                                conditionalPanel("input.projSel == 'projTime'",
                                                                 div(i18n$t("Module: Project to New Time"), id="mod"),
                                                                 uiTop('dismo', i18n$t("Species Distribution Modeling")),
                                                                 HTML('<hr>'),
                                                                 projectTime_UI('c8_projectTime'),
                                                                 strong(i18n$t("Project model to new time for current extent")), br(), br(),
                                                                 actionButton('goProjectTime', i18n$t("Project"))),
                                                conditionalPanel("input.projSel == 'mess'",
                                                                 div(i18n$t("Module: Calculate Environmental Similarity"), id="mod"),
                                                                 uiTop('dismo', i18n$t("Species Distribution Modeling")),
                                                                 HTML('<hr>'),
                                                                 envSimilarity_UI('c8_envSimilarity'),
                                                                 strong(i18n$t("Calculate MESS for current extent")), br(), br(),
                                                                 actionButton('goEnvSimilarity', i18n$t("Calculate MESS"))),
                                                br(), br(),
                                                strong(i18n$t("Reset projection raster")), br(), br(),
                                                actionButton("goResetProj", i18n$t("Reset")),
                                                HTML('<hr>'),
                                                selectInput('projFileType', label = i18n$t("Select download file type"),
                                                            choices = list("GRD" = 'raster', "ASCII" = 'ascii', "GeoTIFF" = 'GTiff',
                                                                           "PNG" = "png")),
                                                strong(i18n$t("Download displayed raster")), br(), br(),
                                                downloadButton('dlProj', i18n$t("Download")),
                                                HTML('<hr>'),
                                                uiBottom("Jamie M. Kass, Gonzalo E. Pinilla-Buitrago, Bruno Vilela, Robert P. Anderson", 'dismo', 'Robert J. Hijmans, Steven Phillips, John Leathwick, Jane Elith')
                               ),
                               # SESSION CODE ####
                               conditionalPanel("input.tabs == 'rmd'",
                                                h4(i18n$t("Download Session Code")),
                                                HTML('<hr>'),
                                                uiTop('rmarkdown', i18n$t("Dynamic Documents for R")),
                                                uiTop('knitr', i18n$t("A General-Purpose Package for Dynamic Report Generation in R")),
                                                HTML('<hr>'),
                                                selectInput('rmdFileType', label = i18n$t("Select download file type"),
                                                            choices = list("Rmd", "PDF", "HTML", "Word")),
                                                downloadButton('dlRMD', i18n$t("Download Session Code")),
                                                HTML('<hr>'),
                                                uiBottom("Jamie M. Kass, Gonzalo E. Pinilla-Buitrago, Bruno Vilela, Robert P. Anderson", 'rmarkdown', 'JJ Allaire, Joe Cheng, Yihui Xie, Jonathan McPherson, 
                                                       Winston Chang, Jeff Allen, Hadley Wickham, Aron Atkins, Rob Hyndman, Ruben Arslan'), br(),
                                                uiBottom(NULL, 'knitr', 'Yihui Xie')
                               )
                             )),
                      # RESULTS WINDOW ####
                      column(8,
                             conditionalPanel("input.tabs != 0 & input.tabs != 'rmd'",
                                              div(id = "wallaceLog", class = "scrollbox", htmlOutput("log")),
                                              absolutePanel(top = -10, right = 20, width = 150, draggable = TRUE,
                                                            selectInput("bmap", i18n$t("Change Base Map"), 
                                                                        choices = c('ESRI Topo'="Esri.WorldTopoMap",
                                                                                    'Stamen Terrain'="Stamen.Terrain",
                                                                                    'Open Topo'="OpenTopoMap",
                                                                                    'ESRI Imagery'="Esri.WorldImagery",
                                                                                    'ESRI Nat Geo'='Esri.NatGeoWorldMap'),
                                                                        selected = "Esri.WorldTopoMap")),
                                              absolutePanel(top = 60, right = 20, width = 150, draggable = TRUE,
                                                            uiOutput("modSelUI")),
                                              absolutePanel(top = 60, right = 180, width = 150, draggable = TRUE,
                                                            uiOutput("envSelUI"))
                             ),
                             br(),
                             conditionalPanel("input.tabs != 'rmd' & input.tabs != 0",
                                              tabsetPanel(id = 'main',
                                                          tabPanel(i18n$t('Map'), leaflet::leafletOutput("map", height=600)),
                                                          tabPanel(i18n$t('Occs Tbl'), br(), br(), DT::dataTableOutput('occTbl')),
                                                          tabPanel(i18n$t('Results'), 
                                                                   conditionalPanel("input.tabs == 3", verbatimTextOutput('envsPrint')),
                                                                   conditionalPanel("input.tabs == 6", uiOutput('evalTbls')),
                                                                   conditionalPanel("input.tabs == 7 && input.visSel == 'response'",
                                                                                    imageOutput('respPlots')),
                                                                   conditionalPanel("input.tabs == 7 && input.visSel == 'bcPlots' && input.enmSel == 'BIOCLIM'",
                                                                                    imageOutput('bcEnvelPlot')),
                                                                   conditionalPanel("input.tabs == 7 && input.visSel == 'mxEval'  && input.enmSel == 'Maxent'",
                                                                                    imageOutput('mxEvalPlots'))
                                                          ),
                                                          tabPanel(i18n$t('Component Guidance'), uiOutput('gtext_comp')),
                                                          tabPanel(i18n$t('Module Guidance'), uiOutput('gtext_mod'))
                                              )
                             ),
                             conditionalPanel("input.tabs == 'rmd'",
                                              column(8,
                                                     includeMarkdown("Rmd/text_sessionCode.Rmd")
                                              )
                             ),
                             conditionalPanel("input.tabs == 0",
                                              tabsetPanel(id = 'introTabs',
                                                          tabPanel(i18n$t('Intro'), includeMarkdown("Rmd/text_intro.Rmd")),
                                                          tabPanel(i18n$t('About'),
                                                                   fluidRow(
                                                                     column(8, includeMarkdown("Rmd/text_about.Rmd")
                                                                     )
                                                                   )
                                                          )
                                              )
                             )
                      )
             )
  )
))
