---
title: "tab7_respCurves"
output: html_document
---

### **モジュール:** ***応答曲線のプロット*** 
	
**背景**  

モデルのパフォーマンスに加えて、研究者はモデルの応答(好適度)と説明変数の間の関係にもしばしば関心を持っています。在-背景モデルは、加法モデルの一種であるのが普通です。例えば、Maxentモデルでの推定好適度は、各フィーチャによる寄与の合計を表しています(フィーチャとは、Maxentモデルを構成している説明変数とその関数、たとえば気温の二次関数、など。Phillips et al. 2006)。したがって、 好適度と個々の説明変数の値の関係は(分析範囲で利用可能な環境を考慮しながら)、一般に「応答曲線」と呼ばれるプロットとして表現することができます(Elith and Graham 2009)。*Wallace*は`dismo`パッケージによって、モデルの応答(好適度)をｙ軸に、(他の変数がすべて中央値にあるときの)ある説明変数をx軸にプロットして、周辺応答曲線（訳注；ある説明変数の値の変化に対応した推定好適度の変化のグラフ。“周辺（marginal）”とは、注目している変数以外の説明変数は、中央値などの特定の値に固定されているという意味）を作図します。

*Wallace*では、(BIOCLIMのような)モデル構築で背景値を考慮しない在のみモデルに対する応答曲線は生成されません。このようなモデルでは背景値は考慮されないので、分析範囲においてそれぞれの環境が見られる頻度が違っていれば、モデルの出力にバイアスがかかります。したがって、｢応答曲線｣と似たものをBIOCIMの地理的予測から計算することはできますが、現実には(環境の頻度によるバイアスがかかった)単なるヒストグラムであって、存在している環境をどのような相対頻度で利用しているか(すなわち好適度)を示す真の応答曲線とはいえません。

**実装** 

このモジュールでは、Rパッケージの`dismo`のプロット機能を使用します。

ユーザーはまずモデルを選択する必要があります。Maxentの場合、手順6: **モデル構築**で選択した`ENMeval`の設定によっては、選択肢が複数になることがあります。次に、ユーザーは応答曲線を見たい説明変数を選択します。ドロップダウンメニューで選択が可能な説明変数は、構築されたモデルで係数がゼロでない変数(Maxentでのlambda値がゼロでない変数)です。表示中の応答曲線のプロットは画像ファイル(.png)としてダウンロードできます。

**引用文献**

Elith, J., & Graham, C. H. (2009). Do they? How do they? WHY do they differ? On finding reasons for differing performances of species distribution models. *Ecography*. 32: 66-77.
